create table
    revinfo (
        rev INT generated by default as identity,
        revtstmp bigint,
        constraint pk_revinfo primary key (rev)
    );

create table
    category_aud (
        rev int,
        revtype int,
        id bigint generated by default as identity,
        name varchar(255),
        constraint pk_category_aud primary key (id, rev),
        constraint fk_category_aud_revinfo foreign key (rev) references revinfo (rev)
    );

create table
    product_aud (
        rev int,
        revtype int,
        id bigint generated by default as identity,
        name varchar(255),
        price double precision,
        price_mod boolean,
        category_id bigint,
        constraint pk_product_aud primary key (id, rev),
        constraint fk_product_aud_revinfo foreign key (rev) references revinfo (rev)
    );