create table
    category (
        id bigint generated by default as identity,
        name varchar(255) not null,
        constraint pk_category primary key (id),
        constraint uq_category unique (name)
    );

create table
    product (
        id bigint generated by default as identity,
        name varchar(255) not null,
        price double precision not null,
        category_id bigint not null,
        constraint pk_product primary key (id),
        constraint fk_product_category foreign key (category_id) references category (id)
    );