---
server:
  port: 8083

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:catalog-db
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true

eureka:
  instance:
    hostname: localhost  
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
