---
server:
  port: 8080

eureka:
  instance:
    hostname: localhost 
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), /api$\{segment}
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-service/**
          filters:
            - RewritePath=/catalog-service(?<segment>/?.*), /api$\{segment}
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service(?<segment>/?.*), /api$\{segment}
