---
jwt:
  algorithm: RSA512
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvulOtrPYNlUI1voeXUZ+Zvfl4IMm/4TnYSmazvvK9In08s7E1y332bgtVO6e1R7RjMxxcBpa2vZ6a43I7PhY/S5u+WzQuBvWdWErSYuS1lYaIZ3iKy0bDPzfbY/DfXTfYts0D/DBfrY1hh63PZZINOr0r15WrAuvUplFdk0NuKhRBmqABIt0yQnkOvYxgHdqDHnN0TuPVdadWD7bYUpwaicJnLcm2vU0ZkniisQUm25wJM3Hv4OxWLn4jui04sVCqMB/sVKMrY2paR6GIhYVb3MDGArjPWGgDCBoMkQtCNSTxX0tKBhAlYuZh3iVMwRM65GxntBwCT/TeJ8K1InBZQIDAQAB
  issuer: WebshopApplication
  expiration: 10m