---
server:
  port: 8084

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:order-db
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
    hibernate:
      ddl-auto: create

eureka:
  instance:
    hostname: localhost  
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
