
package hu.cubix.zoltan_sipeki.order_service.soap;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ShippingSOAPServiceService", targetNamespace = "http://service.shipping_service.zoltan_sipeki.cubix.hu/", wsdlLocation = "http://localhost:9000/services/ShippingService?wsdl")
public class ShippingSOAPServiceService
    extends Service
{

    private final static URL SHIPPINGSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SHIPPINGSOAPSERVICESERVICE_EXCEPTION;
    private final static QName SHIPPINGSOAPSERVICESERVICE_QNAME = new QName("http://service.shipping_service.zoltan_sipeki.cubix.hu/", "ShippingSOAPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/services/ShippingService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHIPPINGSOAPSERVICESERVICE_WSDL_LOCATION = url;
        SHIPPINGSOAPSERVICESERVICE_EXCEPTION = e;
    }

    public ShippingSOAPServiceService() {
        super(__getWsdlLocation(), SHIPPINGSOAPSERVICESERVICE_QNAME);
    }

    public ShippingSOAPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHIPPINGSOAPSERVICESERVICE_QNAME, features);
    }

    public ShippingSOAPServiceService(URL wsdlLocation) {
        super(wsdlLocation, SHIPPINGSOAPSERVICESERVICE_QNAME);
    }

    public ShippingSOAPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHIPPINGSOAPSERVICESERVICE_QNAME, features);
    }

    public ShippingSOAPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShippingSOAPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IShippingSOAPService
     */
    @WebEndpoint(name = "ShippingSOAPServicePort")
    public IShippingSOAPService getShippingSOAPServicePort() {
        return super.getPort(new QName("http://service.shipping_service.zoltan_sipeki.cubix.hu/", "ShippingSOAPServicePort"), IShippingSOAPService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IShippingSOAPService
     */
    @WebEndpoint(name = "ShippingSOAPServicePort")
    public IShippingSOAPService getShippingSOAPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.shipping_service.zoltan_sipeki.cubix.hu/", "ShippingSOAPServicePort"), IShippingSOAPService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHIPPINGSOAPSERVICESERVICE_EXCEPTION!= null) {
            throw SHIPPINGSOAPSERVICESERVICE_EXCEPTION;
        }
        return SHIPPINGSOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
